api:
  id: "123456"
  client_id: ""
  name: "eapi-example-devops-dev"
  version: "v1"
  logUrl: "https://"
 
papi-notifications:
  protocol: "HTTPS"
  host: "papi-notifications-dev-0u9rh7.mdcq7o.usa-e2.cloudhub.io"
  port: "443"
  basePath: "/api/v1"
  timeout: "15000"