# This workflow will build a MuleSoft project and deploy to CloudHub
name: Build and Deploy to Sandbox
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      target: ${{ vars.TARGET }}
      connectedAppClientId: ${{ vars.CONNECTED_APP_CLIENT_ID }}
      connectedAppClientSecret: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
      runtimeKey: ${{ secrets.RUNTIME_KEY }}
      environment: ${{ vars.ENVIRONMENT }}
      muleEnvironment: ${{ vars.MULE_ENVIRONMENT }}
      businessGroup: "cdc843be-ee07-442b-a612-9968d84e4d05"
    steps:  
    - name: log vars
      run: echo ${env.target}
