# This workflow will build a MuleSoft project and deploy to CloudHub
name: Build and Deploy to Sandbox
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    # needs: build
    runs-on: ubuntu-latest
    environment: qa
    env:
      nexus_username: ${{ vars.NEXUS_USER }}
      nexus_password: ${{ secrets.NEXUS_PASSWORD }}
      conn_app_non_prd_id: ${{vars.CONN_APP_NON_PROD_CLIENT_ID}}
      conn_app_non_prd_secret: ${{secrets.CONN_APP_NON_PROD_CLIENT_SECRET}}
      conn_app_exchange_id: ${{vars.CONN_APP_EXCHANGE_CLIENT_ID}}
      conn_app_exchange_secret: ${{secrets.CONN_APP_EXCHANGE_CLIENT_SECRET}}   
    steps:
    - name: Deploy to CloudHub 2.0
      run: |
        mvn deploy -DskipMunitTests --settings .maven/settings.xml \
        -Dconnected.app.client.id="${{env.conn_app_non_prd_id}}" \
        -Dconnected.app.client.secret="${{env.conn_app_non_prd_secret}}"  
