# This workflow will build a MuleSoft project and deploy to CloudHub
name: Build and Deploy to Sandbox
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    # needs: build
    runs-on: ubuntu-latest
    environment: qa
    env:
      nexus_username: ${{ vars.NEXUS_USER }}
      nexus_password: ${{ secrets.NEXUS_PASSWORD }}
      conn_app_exchange_id: ${{vars.CONN_APP_EXCHANGE_CLIENT_ID}}
      conn_app_exchange_secret: ${{secrets.CONN_APP_EXCHANGE_CLIENT_SECRET}}
      conn_app_non_prd_id: ${{vars.CONN_APP_NON_PROD_CLIENT_ID}}
      conn_app_non_prd_secret: ${{secrets.CONN_APP_NON_PROD_CLIENT_SECRET}}
      anypoint_platform_id: ${{vars.ANYPOINT_PLATFORM_CLIENT_ID}}
      anypoint_platform_secret: ${{secrets.ANYPOINT_PLATFORM_CLIENT_SECRET}}
      mule_env: ${{vars.MULE_ENV}}
      anypoint_platform_visualizer_layer: ${{vars.ANYPOINT_PLATFORM_VISUALIZER_LAYER}}
      runtime_key: ${{ secrets.RUNTIME_KEY }}   
      vcores: ${{ vars.VCORES }}   
      replicas: ${{ vars.REPLICAS }}   
      target: ${{ vars.TARGET }}   
      environment: ${{ vars.ENVIRONMENT }}   
      business_group_id: ${{ vars.BUSINESS_GROUP_ID }}   
      mule_version: ${{ vars.MULE_VERSION }}   
    steps:
    - name: Deploy to CloudHub 2.0
      run: |
        mvn deploy -DmuleDeploy \
        -DskipMunitTests \
        -s .maven/settings.xml 