name: Build and Deploy to NON Prd Environment
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      target: ${{ vars.TARGET }}
      connectedAppClientId: ${{ vars.CONNECTED_APP_CLIENT_ID }}
      connectedAppClientSecret: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
      runtimeKey: ${{ secrets.RUNTIME_KEY }}
      environment: ${{ vars.ENVIRONMENT }}
      muleEnvironment: ${{ vars.MULE_ENVIRONMENT }}
      businessGroup: "cdc843be-ee07-442b-a612-9968d84e4d05"
    steps:    
    - name: Deploy to Sandbox
      run: |
        mvn deploy -DmuleDeploy --settings .maven/settings.xml -DskipMunitTests \
        -DskipDeploymentVerification="true" \
        -Dtarget=${{env.target}} \
        -DconnectedAppClientId=${{env.connectedAppClientId}} \
        -DconnectedAppClientSecret=${{env.connectedAppClientSecret}} \
        -Druntime.key=${{env.runtimeKey}} \
        -Denvironment=${{env.environment}} \
        -Dmule.env=${{env.muleEnvironment}} \
        -DbusinessGroup=${{env.businessGroup}}
