name: Publish package to the Maven Central Repository
on:
  push:
    branches:
      - 'develop'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Print
        run: github.event
