name: Publish package to the Maven Central Repository
on:
  push:
    branches:
      - 'develop'
env:
  VERSION_CONTROL: ${{ vars.VERSION_CONTROL }}-dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Increment Variable
        uses: action-pack/increment@v2
        with:
          name: 'VERSION_CONTROL'
          token: ${{ secrets.GH_LOGIN_TOKEN }}

      - name: Print
        run: echo "${{ env.VERSION_CONTROL }}"
