on:
  push:
    branches:
      - 'develop'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update version in pom.xml (Release only)
        run: echo "here ${{ github.event.release.tag_name }}"
