name: Test, Build And Deploy to PRD
on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]
env:
  version_control: ${{ vars.VERSION_CONTROL_PRD }}
  nexus_username: ${{vars.NEXUS_USER}}
  nexus_password: ${{secrets.NEXUS_PASSWORD}}
  conn_app_exchange_id: ${{vars.CONN_APP_EXCHANGE_CLIENT_ID}}
  conn_app_exchange_secret: ${{secrets.CONN_APP_EXCHANGE_CLIENT_SECRET}}
  conn_app_client_id: ${{vars.CONN_APP_CLIENT_ID}}
  conn_app_client_secret: ${{secrets.CONN_APP_CLIENT_SECRET}}
  anypoint_platform_id: ${{vars.ANYPOINT_PLATFORM_CLIENT_ID}}
  anypoint_platform_secret: ${{secrets.ANYPOINT_PLATFORM_CLIENT_SECRET}}
  mule_env: ${{vars.MULE_ENV}}
  anypoint_platform_visualizer_layer: ${{vars.ANYPOINT_PLATFORM_VISUALIZER_LAYER}}
  runtime_key: ${{secrets.RUNTIME_KEY}}
  vcores: ${{vars.VCORES}}
  replicas: ${{vars.REPLICAS}}
  target: ${{vars.TARGET}}
  environment: ${{vars.ENVIRONMENT}} 
  java_version: ${{vars.JAVA_VERSION}}
  release_channel: ${{vars.RELEASE_CHANNEL}}
  business_group_id: ${{vars.BUSINESS_GROUP_ID}}
  business_group: ${{vars.BUSINESS_GROUP}}
  mule_version: ${{vars.MULE_VERSION}}
  clustered: ${{vars.CLUSTERED}}
jobs:       
  deploy:
    runs-on: ubuntu-latest
    environment: prd
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-          
    - name: Deploy to CloudHub 2.0
      run: echo "${{ env.business_group }}"
