name: Test, Build And Deploy to PRD
on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
env:
  version_control: ${{ vars.VERSION_CONTROL_PRD }}
  nexus_username: ${{vars.NEXUS_USER}}
  nexus_password: ${{secrets.NEXUS_PASSWORD}}
  conn_app_exchange_id: ${{vars.CONN_APP_EXCHANGE_CLIENT_ID}}
  conn_app_exchange_secret: ${{secrets.CONN_APP_EXCHANGE_CLIENT_SECRET}}
  conn_app_client_id: ${{vars.CONN_APP_CLIENT_ID}}
  conn_app_client_secret: ${{secrets.CONN_APP_CLIENT_SECRET}}
  anypoint_platform_id: ${{vars.ANYPOINT_PLATFORM_CLIENT_ID}}
  anypoint_platform_secret: ${{secrets.ANYPOINT_PLATFORM_CLIENT_SECRET}}
  mule_env: ${{vars.MULE_ENV}}
  anypoint_platform_visualizer_layer: ${{vars.ANYPOINT_PLATFORM_VISUALIZER_LAYER}}
  runtime_key: ${{secrets.RUNTIME_KEY}}
  vcores: ${{vars.VCORES}}
  replicas: ${{vars.REPLICAS}}
  target: ${{vars.TARGET}}
  environment: ${{vars.ENVIRONMENT}} 
  java_version: ${{vars.JAVA_VERSION}}
  release_channel: ${{vars.RELEASE_CHANNEL}}
  business_group_id: ${{vars.BUSINESS_GROUP_ID}}
  business_group: ${{vars.BUSINESS_GROUP}}
  mule_version: ${{vars.MULE_VERSION}}
  clustered: ${{vars.CLUSTERED}}
jobs:       
  deploy:
    runs-on: ubuntu-latest
    environment: prd
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Upgrade Version
      run: mvn versions:set -DnewVersion="${{ env.version_control }}" -DgenerateBackupPoms=false       
    - name: Print Business Group
      run:  echo "${{ env.business_group }}"      
    - name: Deploy to CloudHub 2.0
      run: |
        mvn deploy -DmuleDeploy -DskipMunitTests --settings .maven/settings.xml \
        -Dconnected.app.client.id="${{ env.conn_app_client_id }}" \
        -Dconnected.app.client.secret="${{ env.conn_app_client_secret }}" \
        -Dprop.anypoint.platform.client_id="${{ env.anypoint_platform_id }}" \
        -Dprop.anypoint.platform.client_secret="${{ env.anypoint_platform_secret }}" \
        -Dprop.anypoint.platform.visualizer.layer="${{ env.anypoint_platform_visualizer_layer }}" \
        -Dprop.mule.env="${{ env.mule_env }}" \
        -Dprop.runtime.key="${{ env.runtime_key }}" \
        -Dch.vcores="${{ env.vcores }}" \
        -Dch.replicas="${{ env.replicas }}" \
        -Dch.target="${{ env.target }}" \
        -Dch.environment="${{ env.environment }}" \
        -Dch.business.group="${{ env.business_group }}" \
        -Dch.mule.version="${{ env.mule_version }}" \
        -Dch.java.version="${{ env.java_version }}" \
        -Dch.release.channel="${{ env.release_channel }}" \
        -Dch.clustered="${{ env.clustered }}"
