on:
  push:
    branches:
      - 'develop'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_LOGIN_TOKEN }}
          ref: ${{ github.head_ref }}
          
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Automated Github Action Maven Version Bump
        id: bump
        uses: mickem/gh-action-bump-maven-version@v1.0.0
            
      - name: Deploy project
        if: steps.bump.outputs.bumped == false
        run: mvn deploy
